name: proxy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_TOKEN }} ${{ secrets.DOCKER_HOST }}
      - name: Docker Build
        run: docker build -f ./Dockerfile -t ${{ secrets.CONTAINER_NAME }} .
      - name: Tags
        run: |
          docker tag ${{ secrets.CONTAINER_NAME }} ${{ secrets.DOCKER_HOST }}/${{ secrets.CONTAINER_NAME }}:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_HOST }}/${{ secrets.CONTAINER_NAME }}:latest
